# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|

  config.ssh.username = ''

  config.vm.provider :openstack do |os|
    os.openstack_auth_url = ENV['OS_AUTH_URL'] #'http://IP:PORT/v2.0'#
    os.username           = ENV['OS_USERNAME'] #'facebookUserID'#
    os.password           = ENV['OS_PASSWORD'] #'Pass allowed in web console manager'#
    os.tenant_name        = ENV['OS_TENANT_NAME'] #'facebookUserID'#The projectID is the same userID
    os.region             = ENV['OS_REGION_NAME'] #'RegionOne' work's fine#
  end

    config.vm.define 'userver-1' do |s|
     s.vm.provider :openstack do |os, override|
      override.ssh.username = 'ubuntu'
      os.server_name        = 'userver-1'
      os.image              = 'Ubuntu16.04' #verify images aviability in the web console
      os.flavor             = 'm1.small' # work's fine
      os.security_groups    = ['default']
      os.networks           = ['red1.1'] #previous create in the web console
      os.floating_ip_pool   = 'public'
    end
   end

  config.vm.define 'userver-2' do |s|
    s.vm.provider :openstack do |os, override|
      override.ssh.username = 'ubuntu'
      os.server_name        = 'userver-2'
      os.image              = 'Ubuntu14.04'  #verify images aviability in the web console
      os.flavor             = 'm1.small' #work's fine
      os.security_groups    = ['default']
      os.networks           = ['red1.1'] #previous create in the web console
      os.floating_ip_pool   = 'public'
    end
  end

  #internet access is required
  N = 2
  (1..N).each do |machine_id|
    config.vm.define "userver-#{machine_id}" do |machine|
      machine.vm.hostname = "userver-#{machine_id}"
      config.vm.provision "chef_solo" do |chef|
        chef.add_recipe "packages-#{machine_id}"
      end
    end
  end

end
