- hosts: webserver
  sudo: true
  tasks:
  - name: Actualizar cache
    apt: update_cache=yes
  - name: Instalar Git
    apt: name=git state=present
  - name: Instalar MongoDB
    apt: name=mongodb state=present
  - name: Instalar NodeJS
    apt: name=nodejs state=present
    apt: name=npm state=present
  - name: Instalar mongoose
    npm: name=mongoose global=yes


