user = "mmaguero"
numServers = 2

Vagrant.configure(2) do |config|

  (1..numServers).each do |i|

    config.vm.define "server_#{i}" do |server|
      server.vm.provider "docker" do |d|
        d.build_dir = "#{i}"
        d.build_args = ["-t#{user}/server_#{i}"]
        d.create_args = ["-it"]
      end
    end

  end

end
